name: Tests

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [0.0.194]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup sst
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Capture sst version installed
        run: |

          export SST_VERSION=$( sst version )
          echo 'SST_VERSION_INSTALLED<<EOF' >> $GITHUB_ENV
          sst version >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Verify
        shell: python
        env:
          SST_VERSION_EXPECTED: ${{ matrix.version }}
        run: |
          import sys, os
          sys.exit(
              int(not os.environ["SST_VERSION_EXPECTED"] in os.environ["SST_VERSION_INSTALLED"])
          )
